# Generated by Django 5.0.6 on 2024-07-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descriptionm',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='cours',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.department'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
